### ISSUE TITLE
Makerspace and IT how to

### ISSUE THREAD

**Issue by Thebestbmxer** [infinity-spark-jbmdl/afwerx-guides#15]
<h2>Makerspace and IT Infrastructure</h2>

<h2><span style="text-decoration:underline;">How to Guide</span>: Research, Research, Research</h2>

<h4>Makerspace: Build specific requirements from vision and goals, visit other makerspaces for inspiration</h4>

<h4>Partners</h4>

*   Communications Sq, Contracting Sq, PA, Civil Engineering Sq, Legal, Volunteer (day laborers)
*   Hats - GPC, ITEC, Facility Manager

<h4>Materials and Equipment - Space, use case (training space) and accessibility will determine needs (do not purchase yourself out of collaboration)</h4>

<h4>
        Essentials - Proper Education, Software, Maintenance tools, Safety equipment, Security</h4>

<h4>IT Infrastructure:</h4>

<h4>Partners</h4>

*   Communication Sq, Contracting Sq, Legal
*   Hats - GPC, ITEC, Facility Manager
<h4>
        Systems - High intensity, needs will drive purchase (3D rendering, VR, AR) will be out of the ordinary purchasing </h4>

***Most purchases will be outside of ordinary and need to be coordinated through CS and CONS.**

<h2>References:</h2>

<h3>IT</h3>

**BACKGROUND:**  Charted in 2016, AMC’s Spark program now encompasses **(XX)** individual, base-level innovation hubs.  While each hub is structured differently, most employ some form of a prototyping lab, designed to test Airman-developed solutions and commercial off-the-shelf systems (COTS) prior to rapid implementation.  To do this, many labs have (or are planning to) procured non-traditional technology including 3D printers, VR systems, 3D scanners and Internet of Things (IoT) devices.  Due to the requirement of liaising with industry and educational institutions via commercial applications like Skype, Hangouts, Slack, Trello, etc., most innovation labs follow AFWERX’ lead in operating primarily off the protected Air Force NIPRnet (AFNet), unless required to share FOUO or classified information. 

**PROBLEM STATEMENT:** DoDI and AFMAN Guidance for the procurement of Information Technology (IT) has not been updated to allow for the rapid prototyping and equipping nature of the Spark innovation effort. Depending on interpretation of References 1-4 below, specifically the definition of what constitutes “Air Force IT hardware,” one could argue that any electrical device capable of transmitting data like an AppleTV or $0.05 passive RFID tag must be purchased through AFWay from a vendor via an existing offering or new contract. This process can take weeks to months for each item, and is often much more expensive than purchasing from approved GPC vendors like GSA Advantage or Amazon (this is why units routinely spend more than $2K each to purchase $400 iPads, for example).  

<h4>Reference 1: AFMAN 17-1203 (IT Accountability)</h4>

**2.2.1.** All **AF IT hardware** (including PWCS) will be procured using applicable AF Information Technology Commodity Council (ITCC) enterprise buying programs via AFWay at https://www.afway.af.mil, (e.g. Client Computing Solutions Quantum Enterprise Buy [CCS QEB], Digital Printing & Imaging [DPI], Cellular Services & Devices BPAs). All AF IT hardware not purchased through ITCC buying programs (CCS, DPI, & CSD BPAs), are mandated to use the NETCENTS-2 contracts, which enable delivery of products, services and solutions that adhere to the AF Enterprise Architecture, (T-1).

<h4>Reference 2: AFI 64-117 (GPC Program)</h4>

**7.12.5** All **Air Force IT hardware** will be acquired using the applicable enterprise buying programs through AFWay (e.g. Quantum Enterprise Buy (QEB), Digital Printing & Imaging (DPI), Cellular Services and Devices Blanket Purchase Agreements) unless waived by the MAJCOM CIO/A6 through the AFWay process (T-2). 

<h4>Reference 3: AFMAN 17-1301 (COMPUSEC)</h4>

**3.5.** Information Technology Asset Procurement. Comply with evaluation and validation requirements in DoDI 8500.01 for **all IT services, hardware, firmware, software components, or products incorporated into DoD ISs.**

**3.5.1.** Follow the guidance in AFMAN 17-1203 and the AF Information Technology Commodity Council (ITCC) guidance available on the AF Portal or AFWAY (https://www.afway.af.mil/) for procurement activities of all IT hardware, cellular, and peripheral devices (e.g., desktops, laptops, servers, commercial mobile devices [CMDs], multifunction devices [MFDs] printers, scanners, and wireless peripheral devices).

<h4>Reference 4: DoDI 8500 (IT)</h4>

h. Information Technology 

(1) **All IT that receives, processes, stores, displays, or transmits DoD information will be acquired,** configured, operated, maintained, and disposed of consistent with applicable DoD cybersecurity policies, standards, and architectures.

**RECOMMENDATION:**  Seek official AMC/A6 interpretation of what constitutes AF IT hardware.  Specifically, allow AMC Spark hubs to rapidly develop and acquire COTS solutions outside the traditional Comm/AFWay purchasing process when the acquisition meets ALL of the following stipulations:

*   Not intended to operate on the AFNet, nor transmit/receive FOUO or classified information (complies with references 3 & 4).
*   Purchased for use by an official AMC Spark Office for innovation (prototyping/modernization) efforts only
*   Complies with all applicable GPC/Contracting regulations regarding purchase limits, contracts and approved vendors. 

<h2>GPC</h2>

<h4>AFI64-117  22 JUNE 2018 </h4>

<h5>CHAPTER 8</h5>

<h5>PROHIBITIONS FOR GPC AND CONVENIENCE CHECKS</h5>

**8.24.**  Travel Related Expenses.  Any expenses associated with official Government travel, or temporary duty, supported by travel orders and reimbursed on a travel voucher which includes rental/lease of motor vehicles, purchase of airline, bus, train tickets, fuel, meals, drinks, lodging, or other travel or subsistence costs are prohibited. (T-0)  Individual employees should use their issued Government Travel Card (GTC) for such reimbursable expenses.

**8.34.**  Unmanned Aircraft Systems.  Cardholders are prohibited from the purchase, lease, or contract of any unmanned systems, to include but not limited to, Commercial Off the Shelf Drones, Unmanned Aircraft Systems, Unmanned Aircraft, Ground Control Station, Remote Video Terminal, Electro-Optical/Infrared sensors or any other payload, unmanned ground vehicle/system, or unmanned boat/submersible drone/system.  (T-2)  GPC purchases of spares/replenishment parts for AF approved unmanned systems are not restricted by this AFI.  **Exception:  The GPC may be used to purchase the above if purchase is for Research Development Test & Evaluation purposes.** The GPC holder making Small Unmanned Aircraft Systems purchase under this exception shall notify AFMC/A3V, afmc.a3v@us.af.mil , within 30 days of such purchase. The purchase notification shall include the make, model, and quantity of items purchased.  Purchases made under this exemption are not exempted from applicable Air Force Instructions that govern acquisition, cybersecurity, operation and employment of the purchased items.  (T-2)

8.35.  Preferred Use Memberships.    Preferred use memberships (e.g. Amazon Prime, Wholesale Clubs, etc.) are prohibited for purchase with the GPC (or convenience checks).  (T-1)

<h4>AFI64-117  22 JUNE 2018 33 </h4>

<h5>Chapter 7</h5>

<h5>GOVERNMENT PURCHASE CARD USAGE</h5>

**7.1.2.**  The GPC shall only be used for authorized Government purchases that are valid mission requirements using appropriated funds.  (T-0)  For those organizations that have non-appropriated funds, see AFI 34-275, Air Force Non-Appropriated Fund (NAF) Government Purchase Card Program.  For Chapel Tithes and Offerings Fund GPC usage, see AFI 52-105, Chaplain Corp Resourcing.  Contact local comptroller and/or legal office if any doubt exists regarding the proper use of appropriated funds.

**7.1.3.**  **Ensure that a reasonable price is obtained through price comparisons and other market research methods** as prescribed by FAR Part 10.001, Market Research, Policy and discussed in paragraph 2.2.6.3.  (T-0)  Cardholders should request discounts. When overseas, price comparisons may be made using available prices from existing schedules, other overseas merchants or commercial sources.

**7.1.7.**  The Bureau of Fiscal Service. U.S. Department of Treasury currently limits Government-to-Government card transactions to a daily maximum of $24,999.99 per card.  This includes inter-governmental (i.e., from another DoD agency) and intra-governmental (i.e., from another AF entity).  This rule does not apply to purchases from commercial merchants, either via open market or through GSA Advantage, GSA Global Supply or GSA’s retail stores, as well as from Personal Property or GSA Fleet and Defense Logistics Agency (DLA) Printing Services.  Consult Financial Management for inter-governmental and intragovernmental purchases in excess of $24,999.99 using other mechanisms (e.g. the IntraGovernmental Payment and Collection, or the Invoicing Payment Platform).  (T-0)

**7.1.8.**  **For purchasing of office supplies, all CONUS cardholders shall use the Federal Strategic Sourcing Initiative Program.  (T-0)  All office supply purchases shall be made through either an AbilityOne retailer (in-store or on-line), AF Advantage , or the AFWay contract (for toner only).**  (T-0) If using AF Advantage, cardholders should seek additional price reductions for office supplies.  Requests for deviation from the AF Office Supply Program must be submitted in the form of a waiver request to the Office Supply Commodity Council via email at Office.supply.cc@us.af.mil.  (T-1) Visit the Office Supply EIM page for more information on waiver requests, or to see the complete program Ordering Guide.

**7.1.10.**  **Internet purchases must be limited to those web sites that provide secure transaction safeguards.**

**7.1.12.**  Education & Training Section personnel shall use the GPC to pay for Government or Commercial Off-The-Shelf training and education up to $25,000 for an individual event or planned series of the same training event, activity, or course material.  AF/A1DI approval is required, if course curriculum includes more than 50% of leadership content.  For AF/A1DI approval, submit request via the Civilian Automated Training Input Program (CATNIP).  (T1)  Additional information regarding civilian education and training may be found in AFI 36401, Employee Training and Development.

**7.1.13.**  Organizations may pay for Government or commercial off the shelf training and education with their organization funds up to $25,000; however, if the Government has a need for tailored training or tailored training materials, the requirement shall be placed on Government contract by a warranted contracting officer.  (T-0)  In accordance with DoD Financial Management Regulation, Volume 10, DoD Administrative Instruction Number 40, and AFI 36-401, Employee Training and Development, an SF 182, Authorization, Agreement, Certification of Training must be submitted to the Education & Training Section, and approval obtained, before an individual may attend training.  (T-0)  The approval process requires coordination/concurrence from an individual’s supervisor, second-level supervisor, and the organization’s training coordinator before submitting to the Education & Training Section for review and approval, prior to the training start date.  The Employee Development Manager/Specialist (EDM/S) will ensure requested training is in compliance with all statutory, legal, and administrative requirements.  The cardholder must have an approved SF 182 prior to obligating payment to a vendor.  (T-0)

**7.9.**  Third-Party Payment Service (e.g. PayPal, Google Pay, etc).  Third party payments are categorized as those payments where it is identified that the purchase will be processed via a third party and no goods or other services received (other than payment).  **The cardholder should make every attempt to choose another merchant with whom to procure the goods and/or services.**  When a third-party payment service is used, the cardholder automatically forfeits all dispute rights guaranteed under the GPC purchase by the Bank.  While certain dispute rights may accrue by using the third-party payment service, these rights are not as favorable to the cardholder/Government as those provided pursuant to the GSA SmartPay® contract because the cardholder has to resolve the dispute instead of the Bank.  If it is necessary to procure using a third party payment service, the approving official must ensure there is adequate supporting documentation showing that there was a detailed review of the purchase and that the use of the third party payment service was unavoidable.  Supporting documentation shall be kept in the cardholder’s files.   (T-1)

**7.12.5.**  Communication and computer equipment and software including telephone instruments, cell phones, and expansion plug-in cards must be approved through the local Communications Squadron.  (T-1) **This is required to ensure configuration control, compatibility with AF and joint systems,** and compliance with Section 508 of the Rehabilitation Act, as amended in 1998 (PL 105-220).  Technical solution documentation provided by the Communications and Information Officer should be maintained in the cardholder files.  Secure telephones may not be purchased directly from merchants using the GPC. (T-0) All secure phones must be requisitioned through the standard Base Supply System.  All Air Force IT hardware will be acquired using the applicable enterprise buying programs through AFWay (e.g. Quantum Enterprise Buy (QEB), Digital Printing & Imaging (DPI), Cellular Services and Devices Blanket Purchase Agreements) unless waived by the MAJCOM CIO/A6 through the AFWay process. (T-2)

**7.12.11.**  Visual Information, Electronic Digital Imaging and Video Equipment and Services. The Public Affairs (PA) Office will review and approve all procurement requests for film/digital photographic cameras, video cameras, and photographic printers to ensure compatibility with existing imagery infrastructure and to verify there is no duplication of imagery services available in the PA Office as prescribed in AFI 35-109, Visual Information. (T-3)

**Comment by axelclark** [comment]
This is great!  Do you want to add it as a new file with a pull request?  I would add it at https://github.com/infinity-spark-jbmdl/afwerx-guides/tree/master/docs/spark-cell-101

**Comment by Thebestbmxer** [comment]
Is there any way to add me as a colaborator so that i can just check out a branch and push the whole lot at once insted of updating per page?

Ive been tasked with converting all the doc files in google docs to this.

Thank you,
Evan VanOsdol
________________________________

**Comment by axelclark** [comment]
I sent you the invite.  Even if you aren't a collaborator, you should be able to fork the repo, create a new branch in your forked repo, then change multiple files (multiple commits) in that branch, and finally submit a pull request from that branch with all of those commits.

**Comment by Thebestbmxer** [comment]
Ok, Ill see what I can do.

Thank you,
Evan VanOsdol



________________________________

**Comment by axelclark** [comment]
I tried it out on this pull request: https://github.com/Thebestbmxer/afwerx-guides/pull/1

1. Create a new file [here](https://github.com/infinity-spark-jbmdl/afwerx-guides/tree/master/docs/spark-cell-101)
2. Select create new branch in your fork
3. Add additional files in the new branch of your fork (not in the infinity-spark repo).  These will be automatically added to your pull request.
